const tvSchedule = [
  {
    startTime: "0:30",
    endTime: "3:30",
    name: "Anarhistice",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "0:00",
    endTime: "0:30",
    name: "Europa iz zraka",
    description: "Daily news updates",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 1",
  },

  {
    startTime: "3:30",
    endTime: "4:30",
    name: "Glazba, glazba",
    description: "Action-packed thriller",
    category: "Dokumentarac",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "4:30",
    endTime: "6:00",
    name: "Noćni glazbeni program",
    description: "Action-packed thriller",
    category: "Film",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "6:00",
    endTime: "7:00",
    name: "Dobro jutro, Hrvatska",
    description: "Action-packed thriller",
    category: "Informativni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "7:00",
    endTime: "10:00",
    name: "Maša i medvjed",
    description: "Action-packed thriller",
    category: "Dječji program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "10:00",
    endTime: "12:00",
    name: "Obitelj čudnih životninja",
    description: "Action-packed thriller",
    category: "Zabavni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "12:00",
    endTime: "15:00",
    name: "Gorski liječnik",
    description: "Action-packed thriller",
    category: "Zabavni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "15:00",
    endTime: "17:30",
    name: "TV izlog",
    description: "Action-packed thriller",
    category: "Informativni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "17:30",
    endTime: "20:30",
    name: "I to je Hrvatska",
    description: "Action-packed thriller",
    category: "Informativni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "20:30",
    endTime: "22:30",
    name: "Večernje vijesti",
    description: "Action-packed thriller",
    category: "Informativni program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "22:30",
    endTime: "24:00",
    name: "Kumovi",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 1",
  },
  {
    startTime: "00:00",
    endTime: "1:00",
    name: "Dolina sreće",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "1:00",
    endTime: "2:30",
    name: "Novi stari slučajevi",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: true,
    channel: "HRT 2",
  },
  {
    startTime: "2:30",
    endTime: "4:00",
    name: "Ko te šiša",
    description: "Action-packed thriller",
    category: "Zabavni program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "4:00",
    endTime: "8:00",
    name: "Nocni program",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "8:00",
    endTime: "11:00",
    name: "Rendžer",
    description: "Action-packed thriller",
    category: "Film",
    isRepeat: true,
    channel: "HRT 2",
  },
  {
    startTime: "11:00",
    endTime: "15:00",
    name: "Mjesto pod suncem",
    description: "Action-packed thriller",
    category: "Dokumentarac",
    isRepeat: false,
    channel: "HRT 2",
  },

  {
    startTime: "15:00",
    endTime: "18:00",
    name: "Teletabisi",
    description: "Action-packed thriller",
    category: "Dječiji program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "18:00",
    endTime: "21:30",
    name: "Glas domovine",
    description: "Action-packed thriller",
    category: "Informativni program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "21:30",
    endTime: "22:30",
    name: "Večer glazbe",
    description: "Action-packed thriller",
    category: "Zabavni program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "22:30",
    endTime: "24:00",
    name: "James Bond",
    description: "Action-packed thriller",
    category: "Odrasli program",
    isRepeat: false,
    channel: "HRT 2",
  },
  {
    startTime: "00:00",
    endTime: "1:30",
    name: "Noćni Filmovi",
    description: "Napeti trileri",
    category: "Odrasli program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "1:30",
    endTime: "2:30",
    name: "Zagonetni Slučajevi",
    description: "Napeti trileri",
    category: "Film",
    isRepeat: true,
    channel: "Nova TV",
  },
  {
    startTime: "2:30",
    endTime: "3:45",
    name: "Komedije Kasno U Noć",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "3:45",
    endTime: "7:00",
    name: "Misterije Do Zore",
    description: "Napeti trileri",
    category: "Film",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "7:00",
    endTime: "9:00",
    name: "Večernji Filmovi",
    description: "Napeti trileri",
    category: "Film",
    isRepeat: true,
    channel: "Nova TV",
  },
  {
    startTime: "9:00",
    endTime: "11:00",
    name: "Istraživanje Tajni",
    description: "Napeti trileri",
    category: "Dokumentarni program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "11:00",
    endTime: "13:00",
    name: "Dječji Filmovi",
    description: "Napeti trileri",
    category: "Dječji program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "13:00",
    endTime: "16:30",
    name: "Posebno Izdanje Vijesti",
    description: "Napeti trileri",
    category: "Informativni program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "16:30",
    endTime: "20:30",
    name: "Opera",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "20:30",
    endTime: "22:00",
    name: "Kasni Noćni Trileri",
    description: "Napeti trileri",
    category: "Film",
    isRepeat: false,
    channel: "Nova TV",
  },
  {
    startTime: "22:00",
    endTime: "22:30",
    name: "Vijesti Nove TV",
    description: "Napeti trileri",
    category: "Informativni program program",
    isRepeat: true,
    channel: "Nova TV",
  },
  {
    startTime: "22:30",
    endTime: "24:00",
    name: "Zlatni kavez",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: true,
    channel: "Nova TV",
  },

  {
    startTime: "00:00",
    endTime: "2:00",
    name: "To je VOYO",
    description: "Napeti trileri",
    category: "Odrasli program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "2:00",
    endTime: "3:30",
    name: "RTL Direkt",
    description: "Napeti trileri",
    category: "Informativni program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "3:30",
    endTime: "5:30",
    name: "Zločinački umovi",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: true,
    channel: "RTL",
  },
  {
    startTime: "5:30",
    endTime: "7:30",
    name: "Pume",
    description: "Napeti trileri",
    category: "Dokumentarac",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "7:30",
    endTime: "9:30",
    name: "Jutarnji program",
    description: "Napeti trileri",
    category: "Informativni program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "9:30",
    endTime: "12:30",
    name: "Power Rangers",
    description: "Napeti trileri",
    category: "Dječji program",
    isRepeat: true,
    channel: "RTL",
  },
  {
    startTime: "12:30",
    endTime: "15:30",
    name: "Dr. No",
    description: "Napeti trileri",
    category: "Film",
    isRepeat: true,
    channel: "RTL",
  },
  {
    startTime: "15:30",
    endTime: "18:30",
    name: "Jazz koncert",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "18:30",
    endTime: "20:30",
    name: "RTL danas",
    description: "Napeti trileri",
    category: "Informativni program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "20:30",
    endTime: "22:00",
    name: "San snova",
    description: "Napeti trileri",
    category: "Zabavni program",
    isRepeat: false,
    channel: "RTL",
  },
  {
    startTime: "22:00",
    endTime: "24:00",
    name: "Životinje u Africi",
    description: "Napeti trileri",
    category: "Dokumentarac",
    isRepeat: false,
    channel: "RTL",
  },
];

export { tvSchedule };
